branch-defaults:
  master:
    environment: HR-System-project-dev
    group_suffix: null
environment-defaults:
  HR-System-project-dev:
    branch: master
    repository: destination
global:
  application_name: HR-System-Projact
  branch: master
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: destination
  sc: git
  workspace_type: Application
